# OperationsCenter:
#   CasC: # Configuration as Code
#     Enabled: true
#     Retriever:
#       secrets:
#         adminPassword: hola
OperationsCenter:
  Platform: eks
  Ingress:
    # OperationsCenter.Ingress.Class -- Ingress class to use for OC and MM ingresses
    # Should be set to the same value as ingress-nginx.controller.ingressClassResource.name if enabled
    Class: alb
    # OperationsCenter.Ingress.Annotations -- annotations to put on Ingress object
    Annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
      alb.ingress.kubernetes.io/success-codes: '200'
      alb.ingress.kubernetes.io/healthy-threshold-count: '2'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'

  ContainerSecurityContext:
    allowPrivilegeEscalation: true
    # capabilities:
    #   drop:
    #     - ALL
    privileged: true
    # runAsGroup: 1000
    # runAsUser: 1000
    # runAsNonRoot: true
    # readOnlyRootFilesystem: true

Persistence:
  # Persistence.StorageClass -- Persistent Volume Storage Class for Jenkins Home
  # If defined, storageClassName: <storageClass>.
  # If set to "-", storageClassName: "", which disables dynamic provisioning.
  # If undefined (the default) or set to null, the default storage class will be used,
  # unless specified otherwise below.
  # If setting OperationsCenter.Platform == gke, a storage class backed with
  # SSD drives will be created by this chart and used automatically.
  #
  # StorageClass: "-"
  StorageClass: 'gp2'
  Size: 5Gi

