# OperationsCenter:
#   CasC: # Configuration as Code
#     Enabled: true
#     Retriever:
#       secrets:
#         adminPassword: hola
OperationsCenter:
  Ingress:
    # OperationsCenter.Ingress.Class -- Ingress class to use for OC and MM ingresses
    # Should be set to the same value as ingress-nginx.controller.ingressClassResource.name if enabled
    Class: alb
    # OperationsCenter.Ingress.Annotations -- annotations to put on Ingress object
    Annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
      alb.ingress.kubernetes.io/success-codes: '200'
      alb.ingress.kubernetes.io/healthy-threshold-count: '2'
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'