# # 3 Kubernetes objects
# # StatefulSet/invincible-gtg
# # Service/invincible-gtg
# # Ingress/invincible-gtg
# ---
# statefulset:
#   apiVersion: "apps/v1"
#   kind: "StatefulSet"
#   metadata:
#     labels:
#       com.cloudbees.cje.tenant: "invincible-gtg"
#       com.cloudbees.cje.type: "master"
#       com.cloudbees.pse.tenant: "invincible-gtg"
#       com.cloudbees.pse.type: "master"
#       tenant: "invincible-gtg"
#       type: "master"
#     name: "invincible-gtg"
#     namespace: "cloudbees-core"
#   spec:
#     selector:
#       matchLabels:
#         com.cloudbees.cje.tenant: "invincible-gtg"
#         com.cloudbees.cje.type: "master"
#         com.cloudbees.pse.tenant: "invincible-gtg"
#         com.cloudbees.pse.type: "master"
#         tenant: "invincible-gtg"
#         type: "master"
#     serviceName: "invincible-gtg"
#     template:
#       metadata:
#         annotations:
#           cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
#         labels:
#           com.cloudbees.cje.tenant: "invincible-gtg"
#           com.cloudbees.cje.type: "master"
#           com.cloudbees.pse.tenant: "invincible-gtg"
#           com.cloudbees.pse.type: "master"
#           tenant: "invincible-gtg"
#           type: "master"
#         name: "invincible-gtg"
#         namespace: "cloudbees-core"
#       spec:
#         affinity:
#           nodeAffinity:
#             requiredDuringSchedulingIgnoredDuringExecution:
#               nodeSelectorTerms:
#               - matchExpressions:
#                 - key: "kubernetes.io/os"
#                   operator: "In"
#                   values:
#                   - "linux"
#           podAntiAffinity:
#             preferredDuringSchedulingIgnoredDuringExecution:
#             - podAffinityTerm:
#                 labelSelector:
#                   matchExpressions:
#                   - key: "com.cloudbees.cje.type"
#                     operator: "In"
#                     values:
#                     - "cjoc"
#                 topologyKey: "kubernetes.io/hostname"
#               weight: 1
#             - podAffinityTerm:
#                 labelSelector:
#                   matchExpressions:
#                   - key: "jenkins"
#                     operator: "In"
#                     values:
#                     - "slave"
#                 topologyKey: "kubernetes.io/hostname"
#               weight: 1
#         containers:
#         - env:
#           - name: "ENVIRONMENT"
#             value: "KUBERNETES"
#           - name: "JAVA_OPTS"
#             value: "-Djenkins.model.Jenkins.slaveAgentPortEnforce=\"true\" -Djenkins.model.Jenkins.slaveAgentPort=\"\
#               50000\" -Dhudson.TcpSlaveAgentListener.port=\"50001\" -DMASTER_GRANT_ID=\"\
#               d447b896-509c-40ef-ab96-ba7d7db98396\" -DMASTER_DOMAIN=\"null\" -DMASTER_INDEX=\"\
#               0\" -DMASTER_OPERATIONSCENTER_ENDPOINT=\"http://cjoc.cloudbees-core.svc.cluster.local/cjoc/\"\
#               \ -Dhudson.lifecycle=\"hudson.lifecycle.ExitLifecycle\" -DMASTER_NAME=\"\
#               invincible-gtg\" -DMASTER_ENDPOINT=\"http://localhost:8080/invincible-gtg/\"\
#               \ -DMASTER_WEBSOCKET=\"false\" -DMASTER_RESOURCE_URL= -XshowSettings:vm\
#               \ -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled\
#               \ -XX:+UseStringDeduplication -Dhudson.slaves.NodeProvisioner.initialDelay=0\
#               \ -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage=cloudbees/cloudbees-core-agent:2.452.1.2\
#               \ -Dcom.cloudbees.jenkins.plugins.kube.ServiceAccountFilter.defaultServiceAccount=jenkins-agents\
#               \ -Dcom.cloudbees.networking.useSubdomain=false -Dcom.cloudbees.networking.protocol=\"\
#               http\" -Dcom.cloudbees.networking.hostname= -Dcom.cloudbees.networking.port=80\
#               \ -Dcom.cloudbees.networking.operationsCenterName=\"cjoc\""
#           - name: "JENKINS_OPTS"
#             value: "--prefix=/invincible-gtg/"
#           - name: "KUBERNETES_JENKINS_URL"
#             value: "http://invincible-gtg.cloudbees-core.svc.cluster.local/invincible-gtg/"
#           image: "cloudbees/cloudbees-core-mm:2.452.1.2"
#           livenessProbe:
#             httpGet:
#               path: "/invincible-gtg/whoAmI/api/json?tree=authenticated"
#               port: 8080
#             initialDelaySeconds: 300
#             periodSeconds: 10
#             timeoutSeconds: 10
#           name: "jenkins"
#           ports:
#           - containerPort: 8080
#             name: "http"
#           - containerPort: 50000
#             name: "jnlp"
#           readinessProbe:
#             failureThreshold: 0
#             httpGet:
#               path: "/invincible-gtg/whoAmI/api/json?tree=authenticated"
#               port: 8080
#             initialDelaySeconds: 0
#             timeoutSeconds: 0
#           resources:
#             limits:
#               cpu: "1.000000"
#           volumeMounts:
#           - mountPath: "/tmp"
#             name: "tmp"
#           - mountPath: "/var/jenkins_home"
#             name: "jenkins-home"
#         enableServiceLinks: false
#         securityContext:
#           fsGroup: 1000
#         serviceAccountName: "jenkins"
#         terminationGracePeriodSeconds: 1200
#         volumes:
#         - emptyDir: {}
#           name: "tmp"
#     volumeClaimTemplates:
#     - apiVersion: "v1"
#       kind: "PersistentVolumeClaim"
#       metadata:
#         name: "jenkins-home"
#       spec:
#         accessModes:
#         - "ReadWriteOnce"
#         resources:
#           requests:
#             storage: "50Gi"
# deployment: null
# pvc: null
# service:
#   apiVersion: "v1"
#   kind: "Service"
#   metadata:
#     labels:
#       com.cloudbees.cje.tenant: "invincible-gtg"
#       com.cloudbees.cje.type: "master"
#       com.cloudbees.pse.tenant: "invincible-gtg"
#       com.cloudbees.pse.type: "master"
#       tenant: "invincible-gtg"
#       type: "master"
#     name: "invincible-gtg"
#     namespace: "cloudbees-core"
#   spec:
#     ports:
#     - name: "http"
#       port: 80
#       protocol: "TCP"
#       targetPort: 8080
#     - name: "agent"
#       port: 50001
#       protocol: "TCP"
#       targetPort: 50000
#     selector:
#       com.cloudbees.cje.tenant: "invincible-gtg"
#       com.cloudbees.cje.type: "master"
#       com.cloudbees.pse.tenant: "invincible-gtg"
#       com.cloudbees.pse.type: "master"
#       tenant: "invincible-gtg"
#       type: "master"
# ingress:
#   apiVersion: "networking.k8s.io/v1"
#   kind: "Ingress"
#   metadata:
#     annotations:
#       nginx.ingress.kubernetes.io/proxy-body-size: "50m"
#       nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
#       nginx.ingress.kubernetes.io/ssl-redirect: "false"
#       kubectl.kubernetes.io/last-applied-configuration: "{\"apiVersion\":\"networking.k8s.io/v1\"\
#         ,\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{\"kubernetes.io/tls-acme\"\
#         :\"false\",\"nginx.ingress.kubernetes.io/app-root\":\"/cjoc/teams-check/\"\
#         ,\"nginx.ingress.kubernetes.io/proxy-body-size\":\"50m\",\"nginx.ingress.kubernetes.io/proxy-request-buffering\"\
#         :\"off\",\"nginx.ingress.kubernetes.io/ssl-redirect\":\"false\"},\"labels\"\
#         :{\"app.kubernetes.io/instance\":\"cloudbees-core\",\"app.kubernetes.io/managed-by\"\
#         :\"Helm\",\"app.kubernetes.io/name\":\"cloudbees-core\",\"argocd.argoproj.io/instance\"\
#         :\"cloudbees-core\",\"helm.sh/chart\":\"cloudbees-core-3.17821.0_5cfcf804cfad\"\
#         },\"name\":\"cjoc\",\"namespace\":\"cloudbees-core\"},\"spec\":{\"ingressClassName\"\
#         :\"nginx\",\"rules\":[{\"http\":{\"paths\":[{\"backend\":{\"service\":{\"\
#         name\":\"cjoc\",\"port\":{\"number\":80}}},\"path\":\"/cjoc\",\"pathType\"\
#         :\"Prefix\"}]}}]}}\n"
#       nginx.ingress.kubernetes.io/app-root: "/cjoc/teams-check/"
#       kubernetes.io/tls-acme: "false"
#     labels:
#       com.cloudbees.cje.tenant: "invincible-gtg"
#       com.cloudbees.cje.type: "master"
#       com.cloudbees.pse.tenant: "invincible-gtg"
#       com.cloudbees.pse.type: "master"
#       tenant: "invincible-gtg"
#       type: "master"
#     name: "invincible-gtg"
#     namespace: "cloudbees-core"
#   spec:
#     ingressClassName: "nginx"
#     rules:
#     - http:
#         paths:
#         - backend:
#             service:
#               name: "invincible-gtg"
#               port:
#                 name: "http"
#           path: "/invincible-gtg/"
#           pathType: "Prefix"
# additionalResources: []
# allResources:







# - apiVersion: "apps/v1"
#   kind: "StatefulSet"
#   metadata:
#     labels:
#       com.cloudbees.cje.tenant: "invincible-gtg"
#       com.cloudbees.cje.type: "master"
#       com.cloudbees.pse.tenant: "invincible-gtg"
#       com.cloudbees.pse.type: "master"
#       tenant: "invincible-gtg"
#       type: "master"
#     name: "invincible-gtg"
#     namespace: "cloudbees-core"
#   spec:
#     selector:
#       matchLabels:
#         com.cloudbees.cje.tenant: "invincible-gtg"
#         com.cloudbees.cje.type: "master"
#         com.cloudbees.pse.tenant: "invincible-gtg"
#         com.cloudbees.pse.type: "master"
#         tenant: "invincible-gtg"
#         type: "master"
#     serviceName: "invincible-gtg"
#     template:
#       metadata:
#         annotations:
#           cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
#         labels:
#           com.cloudbees.cje.tenant: "invincible-gtg"
#           com.cloudbees.cje.type: "master"
#           com.cloudbees.pse.tenant: "invincible-gtg"
#           com.cloudbees.pse.type: "master"
#           tenant: "invincible-gtg"
#           type: "master"
#         name: "invincible-gtg"
#         namespace: "cloudbees-core"
#       spec:
#         affinity:
#           nodeAffinity:
#             requiredDuringSchedulingIgnoredDuringExecution:
#               nodeSelectorTerms:
#               - matchExpressions:
#                 - key: "kubernetes.io/os"
#                   operator: "In"
#                   values:
#                   - "linux"
#           podAntiAffinity:
#             preferredDuringSchedulingIgnoredDuringExecution:
#             - podAffinityTerm:
#                 labelSelector:
#                   matchExpressions:
#                   - key: "com.cloudbees.cje.type"
#                     operator: "In"
#                     values:
#                     - "cjoc"
#                 topologyKey: "kubernetes.io/hostname"
#               weight: 1
#             - podAffinityTerm:
#                 labelSelector:
#                   matchExpressions:
#                   - key: "jenkins"
#                     operator: "In"
#                     values:
#                     - "slave"
#                 topologyKey: "kubernetes.io/hostname"
#               weight: 1
#         containers:
#         - env:
#           - name: "ENVIRONMENT"
#             value: "KUBERNETES"
#           - name: "JAVA_OPTS"
#             value: "-Djenkins.model.Jenkins.slaveAgentPortEnforce=\"true\" -Djenkins.model.Jenkins.slaveAgentPort=\"\
#               50000\" -Dhudson.TcpSlaveAgentListener.port=\"50001\" -DMASTER_GRANT_ID=\"\
#               d447b896-509c-40ef-ab96-ba7d7db98396\" -DMASTER_DOMAIN=\"null\" -DMASTER_INDEX=\"\
#               0\" -DMASTER_OPERATIONSCENTER_ENDPOINT=\"http://cjoc.cloudbees-core.svc.cluster.local/cjoc/\"\
#               \ -Dhudson.lifecycle=\"hudson.lifecycle.ExitLifecycle\" -DMASTER_NAME=\"\
#               invincible-gtg\" -DMASTER_ENDPOINT=\"http://localhost:8080/invincible-gtg/\"\
#               \ -DMASTER_WEBSOCKET=\"false\" -DMASTER_RESOURCE_URL= -XshowSettings:vm\
#               \ -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+ParallelRefProcEnabled\
#               \ -XX:+UseStringDeduplication -Dhudson.slaves.NodeProvisioner.initialDelay=0\
#               \ -Dorg.csanchez.jenkins.plugins.kubernetes.pipeline.PodTemplateStepExecution.defaultImage=cloudbees/cloudbees-core-agent:2.452.1.2\
#               \ -Dcom.cloudbees.jenkins.plugins.kube.ServiceAccountFilter.defaultServiceAccount=jenkins-agents\
#               \ -Dcom.cloudbees.networking.useSubdomain=false -Dcom.cloudbees.networking.protocol=\"\
#               http\" -Dcom.cloudbees.networking.hostname= -Dcom.cloudbees.networking.port=80\
#               \ -Dcom.cloudbees.networking.operationsCenterName=\"cjoc\""
#           - name: "JENKINS_OPTS"
#             value: "--prefix=/invincible-gtg/"
#           - name: "KUBERNETES_JENKINS_URL"
#             value: "http://invincible-gtg.cloudbees-core.svc.cluster.local/invincible-gtg/"
#           image: "cloudbees/cloudbees-core-mm:2.452.1.2"
#           livenessProbe:
#             httpGet:
#               path: "/invincible-gtg/whoAmI/api/json?tree=authenticated"
#               port: 8080
#             initialDelaySeconds: 300
#             periodSeconds: 10
#             timeoutSeconds: 10
#           name: "jenkins"
#           ports:
#           - containerPort: 8080
#             name: "http"
#           - containerPort: 50000
#             name: "jnlp"
#           readinessProbe:
#             failureThreshold: 0
#             httpGet:
#               path: "/invincible-gtg/whoAmI/api/json?tree=authenticated"
#               port: 8080
#             initialDelaySeconds: 0
#             timeoutSeconds: 0
#           resources:
#             limits:
#               cpu: "1.000000"
#           volumeMounts:
#           - mountPath: "/tmp"
#             name: "tmp"
#           - mountPath: "/var/jenkins_home"
#             name: "jenkins-home"
#         enableServiceLinks: false
#         securityContext:
#           fsGroup: 1000
#         serviceAccountName: "jenkins"
#         terminationGracePeriodSeconds: 1200
#         volumes:
#         - emptyDir: {}
#           name: "tmp"
#     volumeClaimTemplates:
#     - apiVersion: "v1"
#       kind: "PersistentVolumeClaim"
#       metadata:
#         name: "jenkins-home"
#       spec:
#         accessModes:
#         - "ReadWriteOnce"
#         resources:
#           requests:
#             storage: "50Gi"







# - apiVersion: "v1"
#   kind: "Service"
#   metadata:
#     labels:
#       com.cloudbees.cje.tenant: "invincible-gtg"
#       com.cloudbees.cje.type: "master"
#       com.cloudbees.pse.tenant: "invincible-gtg"
#       com.cloudbees.pse.type: "master"
#       tenant: "invincible-gtg"
#       type: "master"
#     name: "invincible-gtg"
#     namespace: "cloudbees-core"
#   spec:
#     ports:
#     - name: "http"
#       port: 80
#       protocol: "TCP"
#       targetPort: 8080
#     - name: "agent"
#       port: 50001
#       protocol: "TCP"
#       targetPort: 50000
#     selector:
#       com.cloudbees.cje.tenant: "invincible-gtg"
#       com.cloudbees.cje.type: "master"
#       com.cloudbees.pse.tenant: "invincible-gtg"
#       com.cloudbees.pse.type: "master"
#       tenant: "invincible-gtg"
#       type: "master"






# - apiVersion: "networking.k8s.io/v1"
#   kind: "Ingress"
#   metadata:
#     annotations:
#       nginx.ingress.kubernetes.io/proxy-body-size: "50m"
#       nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
#       nginx.ingress.kubernetes.io/ssl-redirect: "false"
#       kubectl.kubernetes.io/last-applied-configuration: "{\"apiVersion\":\"networking.k8s.io/v1\"\
#         ,\"kind\":\"Ingress\",\"metadata\":{\"annotations\":{\"kubernetes.io/tls-acme\"\
#         :\"false\",\"nginx.ingress.kubernetes.io/app-root\":\"/cjoc/teams-check/\"\
#         ,\"nginx.ingress.kubernetes.io/proxy-body-size\":\"50m\",\"nginx.ingress.kubernetes.io/proxy-request-buffering\"\
#         :\"off\",\"nginx.ingress.kubernetes.io/ssl-redirect\":\"false\"},\"labels\"\
#         :{\"app.kubernetes.io/instance\":\"cloudbees-core\",\"app.kubernetes.io/managed-by\"\
#         :\"Helm\",\"app.kubernetes.io/name\":\"cloudbees-core\",\"argocd.argoproj.io/instance\"\
#         :\"cloudbees-core\",\"helm.sh/chart\":\"cloudbees-core-3.17821.0_5cfcf804cfad\"\
#         },\"name\":\"cjoc\",\"namespace\":\"cloudbees-core\"},\"spec\":{\"ingressClassName\"\
#         :\"nginx\",\"rules\":[{\"http\":{\"paths\":[{\"backend\":{\"service\":{\"\
#         name\":\"cjoc\",\"port\":{\"number\":80}}},\"path\":\"/cjoc\",\"pathType\"\
#         :\"Prefix\"}]}}]}}\n"
#       nginx.ingress.kubernetes.io/app-root: "/cjoc/teams-check/"
#       kubernetes.io/tls-acme: "false"
#     labels:
#       com.cloudbees.cje.tenant: "invincible-gtg"
#       com.cloudbees.cje.type: "master"
#       com.cloudbees.pse.tenant: "invincible-gtg"
#       com.cloudbees.pse.type: "master"
#       tenant: "invincible-gtg"
#       type: "master"
#     name: "invincible-gtg"
#     namespace: "cloudbees-core"
#   spec:
#     ingressClassName: "nginx"
#     rules:
#     - http:
#         paths:
#         - backend:
#             service:
#               name: "invincible-gtg"
#               port:
#                 name: "http"
#           path: "/invincible-gtg/"
#           pathType: "Prefix"


# rawExtensions: []
